SELECT P.NAME AS PERSON_NAME, PIZZA_NAME, PZ.NAME AS PIZZERIA_NAME
FROM PERSON P
JOIN PERSON_ORDER PO ON P.ID = PO.PERSON_ID
JOIN MENU M ON PO.MENU_ID = M.ID
JOIN PIZZERIA PZ ON M.PIZZERIA_ID = PZ.ID
ORDER BY 1, 2, 3;