SELECT PIZZA_NAME, PZ.NAME AS PIZZERIA_NAME
FROM PERSON_ORDER PO
INNER JOIN PERSON P ON PO.PERSON_ID = P.ID
INNER JOIN MENU M ON PO.MENU_ID = M.ID
INNER JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID
WHERE P.NAME IN ('Denis','Anna')
ORDER BY 1, 2;