SELECT NAME
FROM PIZZERIA
WHERE ID not in (SELECT PIZZERIA_ID FROM PERSON_VISITS);

SELECT NAME 
FROM PIZZERIA P
WHERE NOT EXISTS (SELECT PIZZERIA_ID FROM PERSON_VISITS PV WHERE P.ID = PV.PIZZERIA_ID);