CREATE MATERIALIZED VIEW mv_dmitriy_visits_and_eats AS
SELECT PZ.NAME AS PIZZERIA_NAME
FROM PERSON_VISITS PV
INNER JOIN PERSON P ON PV.PERSON_ID = P.ID
INNER JOIN PIZZERIA PZ ON PV.PIZZERIA_ID = PZ.ID
INNER JOIN MENU M ON PZ.ID = M.PIZZERIA_ID
WHERE P.NAME = 'Dmitriy'
	AND VISIT_DATE = '2022-01-08'
	AND PRICE < 800;