SELECT ORDER_DATE, CONCAT(PERSON.NAME,' (age:', PERSON.AGE,')') AS PERSON_INFORMATION
FROM PERSON
NATURAL JOIN (SELECT PERSON_ID AS ID, ORDER_DATE FROM PERSON_ORDER) PERSON_ORDER
ORDER BY ORDER_DATE, PERSON_INFORMATION;