SELECT ORDER_DATE, CONCAT(PERSON.NAME,' (age:', PERSON.AGE,')') AS PERSON_INFORMATION
FROM PERSON
INNER JOIN PERSON_ORDER ON PERSON_ORDER.PERSON_ID = PERSON.ID
ORDER BY ORDER_DATE, PERSON_INFORMATION;