SELECT ORDER_DATE AS ACTION_DATE,
	PERSON.NAME AS PERSON_NAME
FROM PERSON_ORDER
INNER JOIN PERSON ON PERSON_ORDER.PERSON_ID = PERSON.ID INTERSECT
SELECT VISIT_DATE AS ACTION_DATE,
	PERSON.NAME AS PERSON_NAME
FROM PERSON_VISITS
INNER JOIN PERSON ON PERSON_VISITS.PERSON_ID = PERSON.ID
ORDER BY ACTION_DATE,
	PERSON_NAME DESC;