SELECT COALESCE(P.NAME, '-') AS PERSON_NAME, VISIT_DATE, COALESCE(PZ.NAME, '-') AS PIZZERIA_NAME
FROM (SELECT * FROM PERSON_VISITS WHERE VISIT_DATE BETWEEN '2022-01-01' AND '2022-01-03') AS PV
FULL JOIN PERSON P ON P.ID = PV.PERSON_ID
FULL JOIN PIZZERIA PZ ON PZ.ID = PV.PIZZERIA_ID
ORDER BY 1, 2, 3;

