SELECT (SELECT NAME FROM PERSON WHERE PERSON.ID = PERSON_ID) AS PERSON_NAME,
       (SELECT NAME FROM PIZZERIA WHERE PIZZERIA.ID = PIZZERIA_ID) AS PIZZERIA_NAME
FROM (SELECT * FROM PERSON_VISITS WHERE VISIT_DATE BETWEEN '2022-01-07' AND '2022-01-09') AS PV
ORDER BY PERSON_NAME, PIZZERIA_NAME DESC;